"""empty message

Revision ID: 43a54e6627ae
Revises: 
Create Date: 2020-08-19 12:45:24.971506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43a54e6627ae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('MESSAGES',
    sa.Column('messageID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('orig_msg', sa.String(length=512), nullable=False),
    sa.Column('jp_msg', sa.String(length=512), nullable=True),
    sa.Column('region', sa.String(length=16), nullable=False),
    sa.Column('username', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('messageID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('MESSAGES')
    # ### end Alembic commands ###
